export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_EMPTY_ITEM = "CART_EMPTY_ITEM";