export const DASHBOARD_ITEMS_REQUEST = "DASHBOARD_ITEMS_REQUEST";
export const DASHBOARD_ITEMS_SUCCESS = "DASHBOARD_ITEMS_SUCCESS"
export const DASHBOARD_ITEMS_FAIL = "DASHBOARD_ITEMS_FAIL";
export const DASHBOARD_ITEMS_RESET = "DASHBOARD_ITEMS_RESET";